### ISSUE TITLE
Blueprint mirroring?

### ISSUE THREAD

**Issue by Next-Door-Tech** [FluffierThanThou/Blueprints#3]
So there have been a few times where I want to mirror a blueprint left-to-right, but with the current version this doesn't seem to be a feature. Could this be added in a future update?

Otherwise, the mod works great! Keep up the good work. :)

**Comment by FluffierThanThou** [comment]
I suspect this might be harder than it sounds, since I'd have to deal with objects of varying sizes, and couldn't rely on the vanilla rotation functions anymore for individual objects. 

I'll put it on the list of things to investigate, but hopefully you'll understand if I'll focus on updating all my mods first...

Either way, thanks for taking the time to create a suggestion here!

**Comment by Next-Door-Tech** [comment]
Yeah, that's no problem. I wasn't really thinking about how to implement it, the thought just came to mind and I didn't see it suggested anywhere else. You've definitely got your work cut out for you with A16 coming up, so don't worry about bells and whistles for now.

Anyway, keep it up!
Cheers!

**Comment by FluffierThanThou** [comment]
I've had a stab at a few naieve implementations of flipping the blueprints, but relative placements with odd-sized buildings do indeed become an issue. I'll have another stab at this soon.

[note to self; find out where the game centers multi-cell things and offset with that]
